version: '3.2'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'quioscoDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
